name: vfss
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.2
  - ipykernel=6.29.5
  - matplotlib=3.8.0
  - numpy=1.26.4
  - openjpeg=2.3.0
  - openpyxl=3.1.5
  - pandas=2.2.1
  -imageio=2.37.0
  - pip:
      - charset-normalizer==3.4.2
      - click==8.2.1
      - idna==3.10
      - imageio-ffmpeg==0.4.3
      - ninja==1.11.1.4
      - opencv-python==4.9.0.80
      - pyspng==0.1.3
      - requests==2.32.3
      - scipy==1.15.3
      - urllib3==2.4.0
